version: '3.1'
services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: guard_gate
            MYSQL_USER: root
            MYSQL_PASSWORD:
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
    adminer:
        image: adminer
        # restart: always
        ports:
            - 5432:5432
        depends_on:
            - db
    api:
        image: api
        depends_on:
            - db
        build: .
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
            - ./public/:/var/www/html/
        ports:
            - 8200:80
